apiVersion: v1
kind: Service
metadata:
  name: valheim1-service
  labels:
    app: valheim1-service
spec:
  type: NodePort
  ports:
    - name: port-1
      nodePort: 31456
      port: 31456
      protocol: UDP
      targetPort: 31456
    - name: port-2
      nodePort: 31457
      port: 31457
      protocol: UDP
      targetPort: 31457
    - name: port-3
      nodePort: 31458
      port: 31458
      protocol: UDP
      targetPort: 31458
  selector:
    app: valheim1
