apiVersion: v1
kind: ConfigMap
metadata:
  name: valheim-player-lists-cm
data:
  adminlist.txt: |-
      SomePlayerNameOrSteamId
  bannedlist: |-
      SomePlayerNameOrSteamId
  permittedlist: |-
      SomePlayerNameOrSteamId
