apiVersion: v1
kind: Service
metadata:
  name: valheim2-service
  labels:
    app: valheim2-service
spec:
  type: NodePort
  ports:
    - name: port-1
      nodePort: 31466
      port: 31466
      protocol: UDP
      targetPort: 31466
    - name: port-2
      nodePort: 31467
      port: 31467
      protocol: UDP
      targetPort: 31467
    - name: port-3
      nodePort: 31468
      port: 31468
      protocol: UDP
      targetPort: 31468
  selector:
    app: valheim2
