apiVersion: v1
kind: Service
metadata:
  name: valheim3-service
  labels:
    app: valheim3-service
spec:
  type: NodePort
  ports:
    - name: port-1
      nodePort: 31476
      port: 31476
      protocol: UDP
      targetPort: 31476
    - name: port-2
      nodePort: 31477
      port: 31477
      protocol: UDP
      targetPort: 31477
    - name: port-3
      nodePort: 31478
      port: 31478
      protocol: UDP
      targetPort: 31478
  selector:
    app: valheim3
