apiVersion: v1
kind: Service
metadata:
  name: valheim3-service
  labels:
    server: valheim-3
spec:
  type: NodePort
  ports:
    - name: port-1
      nodePort: 31636
      port: 31636
      protocol: UDP
      targetPort: 31636
    - name: port-2
      nodePort: 31637
      port: 31637
      protocol: UDP
      targetPort: 31637
    - name: port-3
      nodePort: 31638
      port: 31638
      protocol: UDP
      targetPort: 31638
  selector:
    server: valheim-3
